//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiAngularMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cat_Company
    {
        public System.Guid Id { get; set; }
        public System.Guid CatId { get; set; }
        public System.Guid CompanyId { get; set; }
        public Nullable<int> CatNumber { get; set; }
    }
}
