//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiAngularMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoryMoveCat
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> CatId { get; set; }
        public Nullable<System.Guid> FromCompanyId { get; set; }
        public Nullable<System.Guid> ToCompanyId { get; set; }
        public Nullable<int> NumberCat { get; set; }
        public string ToAddress { get; set; }
        public Nullable<int> StatusSend { get; set; }
        public string Decription { get; set; }
        public string Tag { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ConfirmedBy { get; set; }
        public Nullable<System.DateTime> ConfirmedDate { get; set; }
    }
}
