//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiAngularMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportInvoice
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> CompanyId { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.Guid> SupplierId { get; set; }
        public Nullable<double> SumMoney { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
