//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiAngularMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DemoApiEntities : DbContext
    {
        public DemoApiEntities()
            : base("name=DemoApiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<aspnet_User> aspnet_User { get; set; }
        public virtual DbSet<Cat_Company> Cat_Company { get; set; }
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<CatManufacturer> CatManufacturer { get; set; }
        public virtual DbSet<CatType> CatType { get; set; }
        public virtual DbSet<Company> Company { get; set; }
        public virtual DbSet<Custormer> Custormer { get; set; }
        public virtual DbSet<DetailInvoiceImport> DetailInvoiceImport { get; set; }
        public virtual DbSet<DetailInvoiceSale> DetailInvoiceSale { get; set; }
        public virtual DbSet<HistoryLogin> HistoryLogin { get; set; }
        public virtual DbSet<HistoryMoveCat> HistoryMoveCat { get; set; }
        public virtual DbSet<ImportInvoice> ImportInvoice { get; set; }
        public virtual DbSet<Material> Material { get; set; }
        public virtual DbSet<MenuNew> MenuNew { get; set; }
        public virtual DbSet<RoleInMenu> RoleInMenu { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<SaleInvoice> SaleInvoice { get; set; }
        public virtual DbSet<Supplier> Supplier { get; set; }
        public virtual DbSet<UserInRole> UserInRole { get; set; }
    }
}
