//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiAngularMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleInMenu
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> RoleId { get; set; }
        public string RoleName { get; set; }
        public Nullable<System.Guid> MenuId { get; set; }
        public Nullable<bool> IsShow { get; set; }
        public Nullable<bool> IsAdd { get; set; }
        public Nullable<bool> IsEdit { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<bool> IsExport { get; set; }
        public Nullable<bool> IsPrint { get; set; }
        public Nullable<bool> IsEnable { get; set; }
        public Nullable<bool> IsDisable { get; set; }
        public Nullable<bool> IsAll { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
